name: Test & Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Lint
      run: |
        pip install flake8 ruff
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        ruff --select=E9,F63,F7,F82 .
